# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de21eb0e6aa150070f777fa9897e8c74c804c39fba39fb742707c17ec6c198bf61fe76d4999b66aac65dfaca599605b5867d07c28309ed075ee17f43132892e0

test:
  secret_key_base: 1265f6d304c276e33236cbbb2f5005f3aac0d9c00eb35efb3c6ee44cdc5c7f9c19e34d5296ead4e58a5266eb9ffe79e31022c4820b6107a23dc69823829bc228

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
